Refactor rlrop condition
mozilla/DeepSpeech pull request #3278
Opened 2020-08-25 08:16 UTC by DanBmh

Improve readability.
Split to separate pr from #3268.

2020-08-28 16:28 UTC, lissyx commented on training/deepspeech_training/train.py
> +                    if (FLAGS.reduce_lr_on_plateau and epochs_without_improvement > 0
let's improve a bit more and put each condition on a new line, ending in `and` ?

2020-08-28 16:29 UTC, lissyx requested changes
LGTM but let's take this to the maximum :)

2020-08-29 12:27 UTC, DanBmh commented
Now it's following black style

2020-08-31 10:01 UTC, lissyx requested changes
It's good but your commit is mixed with unrelated things, please rebase properly on master :/

2020-08-31 10:09 UTC, DanBmh commented
> It's good but your commit is mixed with unrelated things, please rebase properly on master :/

?
Did you mix this up with another PR?

2020-08-31 10:14 UTC, DanBmh commented
I can see now what you mean (clicking on your comment links) but I didn't change those files. 

Your link says: Showing 3 changed files with 10 additions and 8 deletions. 
But I can only see 1 changed file with 5 additions and 3 deletions in the overview here

2020-08-31 10:46 UTC, reuben commented
It looks like you merged into this PR instead of rebasing it.

2020-08-31 10:46 UTC, reuben commented
At the bottom of the changes page GitHub shows: You are viewing a condensed version of this merge commit. You can view the full changes here.

2020-08-31 10:59 UTC, DanBmh commented
Thanks @reuben. Now it should be right.

2020-08-31 14:48 UTC, lissyx approved these changes

2020-08-31 14:48 UTC, lissyx commented
> Thanks @reuben. Now it should be right.

Thanks!

2020-08-31 14:49 UTC, merged