Remote I/O Training Setup
mozilla/DeepSpeech pull request #3420
Opened 2020-11-12 22:50 UTC by CatalinVoss

Offering this up as a PR in case it's useful to more people than just me.

This refactors the training code to use a set of I/O helpers that allow for remote file access, right now using TensorFlow's GFIle API, allowing us to pass in files like `gs://my-bucket/my/path` or `hdfs://...`. This can be extended to AWS `s3://...` paths relatively easily.

Most of the refactoring is fairly straightforward. Things get a little bit more complicated with `AudioFile`, since you pass a local file to sox for the conversion. I've just wrapped that into a copy in a tmpfile, since I assume the conversion overhead prevails here and there was a reason for doing things this way.

2020-11-13 03:44 UTC, CatalinVoss commented
…and indeed, it seems that this is pretty slow with files on a network volume. It seems that what's going on is that the `LimitPool` parallelizes over the augmentation, but file loading is still all handled by the parent process – that part is never actually parallelized. So the assumption is that bottleneck is augmentation rather than `load_sample`.

2020-11-13 08:47 UTC, olafthiele commented
My 2 cents: The limiting factor for us is GPU costs. Even a regular HD drive is really slow in comparison to an SSD drive. So loading individual files over the network seems like a bad idea in itself for a large corpus as you can't feed enough data to the GPU. But this is just us and it might be great for testing or first steps as it is quite tedious to fire up a new VM and copy all data there first.

2020-11-14 03:57 UTC, CatalinVoss commented
@olafthiele Yeah, I mean it's always preferred to have files sitting next to the GPU on an SSD, but sometimes that's hard to spin up quickly, as you say. It's certainly pretty common to do this sort of thing, I think (tensorflow and GCP do this for a lot of their training samples on ImageNet), especially if you have a lot of data coming in. It should perform OK as long as you have sufficient parallel readers.

Here, the file reading actually wasn't parallelized. I now did that by [wrapping `Sample`](https://github.com/mozilla/DeepSpeech/pull/3420/commits/be39d3354dc71499b5fa461c8ce2983779b9f262) with a little `PackedSample` class that does the unpacking on the worker process rather than the parent process. That improves performance a lot.

It made this PR a little bit bigger than what I was going for. If you intend to accept, it may be good to test the reader/writer classes affected. I've mainly worried about training and made sure that that all works. Everything should be compatible still with local file-reading and default to the standard builtin functions.

I haven't bothered updating `CSVWriter` or `TarWriter` since I didn't see them used anywhere and figured they're part of the dataset creation process, which you'd probably run locally.

2020-11-16 14:49 UTC, reuben commented
> I haven't bothered updating `CSVWriter` or `TarWriter` since I didn't see them used anywhere and figured they're part of the dataset creation process, which you'd probably run locally.

Sounds reasonable. FYI I'm starting to review this PR now.

2020-11-16 15:11 UTC, reuben requested changes
First pass, going to do some more testing.

2020-11-16 15:11 UTC, reuben commented on training/deepspeech_training/util/io.py
> +    Wrapper that can remove_remote local and remote files like `gs://...`
Looks like a search and replace that went a bit too eager in this file.

2020-11-16 16:02 UTC, reuben commented
Further testing looks fine, so just need to address the comments above before merging.

2020-11-16 16:47 UTC, CatalinVoss commented
Great, will do shortly! Thank you, @reuben!

2020-11-16 21:43 UTC, CatalinVoss commented on training/deepspeech_training/util/io.py
> +    Wrapper around open_remote() method that can handle remote paths like `gs://...`
Yep, this was the aggressive find & replace, as you pointed out :).

2020-11-16 21:45 UTC, CatalinVoss commented on training/deepspeech_training/train.py
> +    return open_remote(os.path.join(os.path.dirname(__file__), fname)).read()
That's right. Fixed another instance of this in `taskcluster.py`

2020-11-16 21:46 UTC, CatalinVoss commented on training/deepspeech_training/util/helpers.py
> +
Yep, I experimented with unordered pool mapping, but it ended up not being the bottleneck.

2020-11-17 09:53 UTC, reuben approved these changes

2020-11-17 09:53 UTC, merged